### ISSUE TITLE
Change global link hover color 

### ISSUE THREAD

**Issue by haskar1** [TheOdinProject/theodinproject#2643] opened 2022-02-14 23:15 UTC
#### Description
Currently, the global link hover color is black. On mobile, after a link is clicked it stays black until you scroll the webpage. Whenever I click on a link in a lesson and finish reading the article, I come back to the TOP webpage and can’t remember where the link I clicked is (until I scroll up or down) because the black color blends in with surrounding text. Changing it to a more recognizable color would make it immediately obvious what link you clicked on and what the next article is. My suggestion is to change the hover color to something more readable, perhaps blue or purple. 

#### Acceptance Criteria:
I believe the hover colors are here:
theodinproject / app/ assets / stylesheets / global.scss

Under “a” and “href” it says hover color is black.

**Comment by KevinMulhern** [comment] 2022-02-14 23:33
Duplicate of https://github.com/TheOdinProject/theodinproject/issues/2532

**Closed by KevinMulhern** 2022-02-14 23:33 UTC
