### ISSUE TITLE
Enhancement: Aligning succes stories

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/theodinproject#4162] opened 2023-09-19 21:51 UTC
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Description of the Feature Request

The success stories on the home page don't line up nicely. I'd suggest removing `items-center` from their parent container to line them up at the start / top. 

## Current alignment (Notice Rob Pando being centered with Cody Loyd and thus being lowered because of the lesser amount of content):

![Screenshot 2023-09-19 at 23 46 43](https://github.com/TheOdinProject/theodinproject/assets/81025586/d4dcef10-6b1a-4678-a57f-a61a1e457b87)
![Screenshot 2023-09-19 at 23 44 50](https://github.com/TheOdinProject/theodinproject/assets/81025586/4024d164-44c2-4b8a-8a16-8524c247497b)

## Suggested (by me) Without `items-center`:

![Screenshot 2023-09-19 at 23 47 06](https://github.com/TheOdinProject/theodinproject/assets/81025586/6642198c-d7ed-4189-a7f9-efadf02fca4c)

If agreed to by another maintainer to make this change, it's a pretty straightforward good first issue.

### Acceptance criteria

- [ ] profile pictures and name are aligned horizontally

**Comment by headlessNode** [comment] 2023-09-20 07:33
@ManonLef hi, If there isn't any first time contributor available then I'd like to work on this issue.

**Comment by KevinMulhern** [comment] 2023-09-22 20:32
You're on a roll finding this UI bugs @ManonLef 💪 

@headlessNode would you still like to work on this one?

**Comment by headlessNode** [comment] 2023-09-23 20:40
@KevinMulhern sure

**Comment by KevinMulhern** [comment] 2023-09-23 20:51
Thanks @headlessNode, its been assigned to you 😎

**Comment by headlessNode** [comment] 2023-09-26 11:23
@KevinMulhern Sorry I was busy couldn't work on this sooner. I just started, I wanted to ask that if I needed to follow the **Running The Odin Project locally** guide for this?

**Comment by KevinMulhern** [comment] 2023-09-27 07:13
@headlessNode epm you'll need the app running locally to work on the app.

**Comment by headlessNode** [comment] 2023-09-27 12:36
@KevinMulhern setting it up for sure was an experience but um I don't see the said issue here? Did someone work on it?

![gbc](https://github.com/TheOdinProject/theodinproject/assets/101793258/07357029-5bfc-43e0-9517-ef664aa834e7)

**Comment by ManonLef** [comment] 2023-09-27 21:55
<img width="1387" alt="Screenshot 2023-09-27 at 23 46 48" src="https://github.com/TheOdinProject/theodinproject/assets/81025586/770d4ccb-a1a3-4bdc-a456-5bf8c34ae214">
Well this is interesting, it looks entirely different for me now. 

I can't find a recent PR that seems to have caused this at a glance. Maybe @KevinMulhern can provide some insights. It could be a recent sass bump or other styling update perhaps, but that doesn't explain the cards :) It looks like a testing branch slipped into a PR somewhere

**Comment by KevinMulhern** [comment] 2023-09-27 23:15
<img width="1365" alt="Screenshot 2023-09-28 at 00 02 35" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/567c6c0e-4ba7-46c1-8879-45cbbf4bf248">

The issue is showing up for me. 🤔 I think it will only happen when Cody's story is in the top row. It has one more line than the others.

To reproduce locally:
1. Move Cody's success story to be the first or second item in [this list](https://github.com/TheOdinProject/theodinproject/blob/main/db/seeds/success_stories.rb#L1).
1. Open the rails console with `$rails c` and destroy success stories `SuccessStory.destroy_all`
2. Run the seeds task again `$ rails db:seed`
3. Start up the server and the issue should be present now

**Comment by headlessNode** [comment] 2023-09-28 09:01
@KevinMulhern yep, I see it now. Removing the .items-center works for the desktop.
![w c](https://github.com/TheOdinProject/theodinproject/assets/101793258/de15b5f8-1c8c-4c10-8723-95f7ba0d180a)

But on mobile devices, removing .items-center causes the children to be aligned to the left side. Not on all mobile devices though, but on some tablets it'll appear weird.
![w c b](https://github.com/TheOdinProject/theodinproject/assets/101793258/e3c9d006-0d2d-470b-9e17-9209d7cb835c)

Any suggestions on how to tackle that?

**Comment by KevinMulhern** [comment] 2023-09-28 19:54
@headlessNode we'll just need a Tailwind breakpoint - something like `items-center sm:items-start` should do the trick.

**Comment by headlessNode** [comment] 2023-09-29 10:40
@KevinMulhern  It results in the same thing. I would suggest creating a custom class and using custom CSS i.e. `.items-center-1280` and `@media (max-width:1280){.items-center-1280{align-items:center}}`. Although, I can't figure out where to add custom CSS :(

**Comment by KevinMulhern** [comment] 2023-09-29 11:18
@headlessNode the breakpoint needs to match whatever we're using to go to a column layout. This works `items-center xl:items-start`.

**Comment by headlessNode** [comment] 2023-09-29 11:31
@KevinMulhern I tried this. It aligns the children to centre on mobile devices but the original issue still exists on the desktop.

**Desktop:**
![gb-n](https://github.com/TheOdinProject/theodinproject/assets/101793258/031b4742-b41b-400e-84a4-1c69d58e2faa)

**Mobile devices**
![gb-s](https://github.com/TheOdinProject/theodinproject/assets/101793258/25748af6-c898-46b6-9fd3-9185bc6644a6)

**Comment by KevinMulhern** [comment] 2023-09-29 11:44
It definitely works, I've tested myself.

How are you testing this @headlessNode? are you using dev tools on the live version of the site or do you have a local copy running on your machine?

If you're testing live, it's probably not going to work for you. We purge any unused Tailwind classes and there likely isn't an `xl:items-center` combination anywhere else.

**Comment by headlessNode** [comment] 2023-09-29 11:51
@KevinMulhern I just confirmed it again, I'm testing it  on the local copy.

**Comment by KevinMulhern** [comment] 2023-09-29 12:04
@headlessNode It _might_ be the an issue with local assets - I've been seeing that pop up more and more lately.

1. Stop the sever
2. Run the `$ rails assets:clobber` task
3. Start the sever back up
4. 🤞

**Comment by headlessNode** [comment] 2023-09-29 12:30
@KevinMulhern completed these steps, still getting the same result. :(

**Comment by headlessNode** [comment] 2023-09-29 12:35
I think the issue here is because the tailwind breakpoints use min-width.

**Comment by KevinMulhern** [comment] 2023-09-29 13:45
It's got to be something else, `items-center xl:items-start` is the Tailwind ™️ way of solving this and is working fine on my end. 

Can you make a PR with what you have please? we'll be able to put it on a review app and make sure something else isn't going on.

**Comment by headlessNode** [comment] 2023-09-29 17:28
@KevinMulhern It was a mistake that I made on the local copy that was causing this issue, I fixed it. Now the solution you suggested is working. Please check.

**Closed** 2023-09-30 08:17 UTC
Labels: Status: In Progress
