### ISSUE TITLE
Link to lesson on admin flags page is broken

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/theodinproject#1840] opened 2021-04-13 08:37 UTC
### Description
We updated the url structure of the app recently so every lesson needs to accessed through its path and course. However we forgot to update the lesson link on the admin project submission flag page.

### Steps to Reproduce
1. Sign up as a new user
2. Open the rails console or database and set the admin attribute to true for the user you created.
3. Go to the google home page project and flag one of the sample project submissions
4. Go to the admin flags page and find the flag you made: localhost:3000/admin/flags
5. Click the link in the lesson row
6. It opens a 404 page 💥 

### Expected
1. Sign up as a new user
2. Open the rails console or database and set the admin attribute to true for the user you created.
3. Go to the google home page project and flag one of the sample project submissions
4. Go to the admin flags page and find the flag you made: localhost:3000/admin/flags
5. Click the link in the lesson row
6. It opens a the lesson page for the project that was flagged

### Additional Details
Replacing the lesson link with something like `path_course_lesson_path(lesson.path, lesson.course, lesson)` should be all there is to this.

**Comment by Nathan-Galipeau** [comment] 2021-04-20 02:17
Has this been taken care of yet?

**Comment by KevinMulhern** [comment] 2021-04-20 17:07
Hi @Nathan-Galipeau, it hasn't. Would you like to take it on? 😄

**Comment by Nathan-Galipeau** [comment] 2021-04-20 17:33
@KevinMulhern On second thought, I'm still in foundations, and I don't have Ruby installed yet, so I'm assuming that I won't be able to complete step 2 in regard to the ordered list. I apologize for the ignorance.

**Comment by Tenacious-Qi** [comment] 2021-04-26 07:18
My first time contributing to the main site! Thanks for the beautifully outlined steps to reproduce. Not sure if it should have been assigned to me first. If so, please let me know and I'll request it be assigned to me first next time. Either way, the link seems to be working properly now.

**Closed** 2021-04-27 16:58 UTC
