### ISSUE TITLE
Chore: Replace deprecated / division

### ISSUE THREAD

**Issue by mgrigoriev8109** [TheOdinProject/theodinproject#4351] opened 2024-01-19 16:21 UTC
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Chore: brief description of chore` format, e.g. `Chore: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Chore description

Running rspec on main prints `DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.` in the terminal`, so figure that should be addressed.

![image](https://github.com/TheOdinProject/theodinproject/assets/43343880/e6a82b19-b560-4dbc-908d-d49bd7fac741)

The top answer in [this SO question](https://stackoverflow.com/questions/71262427/deprecation-warning-using-for-division-outside-of-calc-is-deprecated-and-wi) links to why this is happening and provides possible alternatives.

### Acceptance criteria

- [ ] Replace `/` for division with non-deprecated alternative.

**Comment by Asartea** [comment] 2024-01-19 16:24
This is caused by `dkniffin/active_material`; I have an open PR on that, but that isn't merged yet dkniffin/active_material#90

**Comment by KevinMulhern** [comment] 2024-01-23 18:55
Thanks for doing that @Asartea 💪

**Closed** 2024-07-02 19:20 UTC
Labels: Status: Needs Review, Type: Chore
