### ISSUE TITLE
Feature Request: Changes in UI of the main site [theodinproject.com]

### ISSUE THREAD

**Issue by RajPansuriya** [TheOdinProject/theodinproject#4831] opened 2024-10-07 09:50 UTC
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [X] Would you like to work on this issue?

### Description of the Feature Request

Hello team,
I wanted to propose some minor changes in the UI of site `theodinproject.com`.

![ArcoLinux_2024-10-07_14-28-15](https://github.com/user-attachments/assets/729c4c58-e775-4331-aca0-83d89332b8b8)

As we can observe in the picture, the content/text of the site is currently aligned left. This gives a non-uniform line endings throughout the page.
We can observe same behaviour on Support page and All paths page as well (spaces marked in RED)

![ArcoLinux_2024-10-07_15-10-17](https://github.com/user-attachments/assets/f3bcaed7-f848-4550-8ef4-3ca6a885e434)

I propose thate these text fileds should have `justify` alignemnt. Small change but can enhance the visual of our website.

please correct me if I am wrong or missing something. Also if you feel to go ahead with this proposal I would like to work on this issue.

### Acceptance criteria

Text fileds should be aligned properly on:
- [ ] About page
- [ ] All Paths page
- [ ] Support us page

**Comment by KevinMulhern** [comment] 2024-10-07 16:09
Thanks for the suggestion @RajPansuriya, duplicate of https://github.com/TheOdinProject/theodinproject/issues/4637

**Closed by KevinMulhern** 2024-10-07 16:09 UTC
Labels: Status: Needs Review
