### ISSUE TITLE
Bug: Long username overflowing in Solutions 

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/theodinproject#3362] opened 2022-10-01 03:33 UTC
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:
-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
If a username is really long, it will overflow the container in the solutions list.

<img width="1227" alt="Screen Shot 2022-09-27 at 7 57 20 PM" src="https://user-images.githubusercontent.com/33227096/193385681-1b3a9af3-43df-4186-ad28-e4dd9c5fd42c.png">

**2. How To Reproduce:**

1. Log in
2. Visit the [Weather App Project](https://www.theodinproject.com/lessons/689)
3. Find the really long username and you'll see that it overflows the container

**3. Expected Behavior:**

1. Log in
2. Visit the [Weather App Project](https://www.theodinproject.com/lessons/689)
3. Find the really long username and see it being truncated or wrapped. And the "View Code" and "Live Preview" buttons are correctly placed.

**4. Desktop/Device:**

-   Device:  Macbook
-   OS:  macOS12.6
-   Browser:  Chrome
-   Version: 

**5. Additional Information:**

**Comment by rtins** [comment] 2022-10-03 09:29
Hi. I was looking for that username but couldn't find him. Has this been fixed?
![img2](https://user-images.githubusercontent.com/112586034/193544931-6207d783-07f5-456e-a0e3-14d087c0ad12.jpg)

**Comment by rlmoser99** [comment] 2022-10-03 12:16
I do not believe that this has not been fixed, but it looks like the user might have changed their username or whoever liked their solution could have unliked it and it now it would be buried in the 83 pages of solutions.

**Comment by Mynameisfrostwalker** [comment] 2022-10-03 12:48
I reproduced this using chrome devtools.
![issue](https://user-images.githubusercontent.com/85758325/193580286-c0495f88-8594-4570-8c46-89af832e716e.png)

**Comment by Mynameisfrostwalker** [comment] 2022-10-03 13:33
Can I be assigned to this issue?

**Comment by Mynameisfrostwalker** [comment] 2022-10-03 14:05
I would like to be assigned on this issue

**Comment by rlmoser99** [comment] 2022-10-03 18:07
Before I assign it to @Mynameisfrostwalker, I want to first offer it to @rtins. Just in case they were asking about it being fixed before asking to be assigned this issue.

**Comment by rtins** [comment] 2022-10-07 11:50
Sorry, That PR is not meant to close this. The reason this appeared here is that I mentioned the issue there (because of a similar issue). I will be working on this now.

**Closed** 2022-10-11 06:28 UTC
Labels: Type: Bug, Status: Needs Review
