### ISSUE TITLE
Redesign Fix: Alignment for How It Works 

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#414] opened 2017-04-16 04:39 UTC
This task is to horizontally align the **Learn, Build, Connect** text on the home page.

The screenshot below shows the current misalignment issue.
<img width="1095" alt="screen shot 2017-04-15 at 9 33 35 pm" src="https://cloud.githubusercontent.com/assets/13413986/25068767/5ba0e5ae-2223-11e7-8dce-8739c8bf4929.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by arun1595** [comment] 2017-04-23 20:38
@faisal3389 is working on this.

**Comment by faisal3389** [comment] 2017-04-24 06:59
Submitted the pull request

**Comment by faisal3389** [comment] 2017-04-24 07:41
@arun1595 @adachiu @KevinMulhern I'm getting the following error 

All checks have failed
1 failing check
continuous-integration/travis-ci/pr — The Travis CI build failed

![image](https://cloud.githubusercontent.com/assets/16716470/25326767/36ab2b42-28ef-11e7-929d-98dc04f684bd.png)


can you help me resolve this. I'm not getting what the issue is.

**Comment by KevinMulhern** [comment] 2017-04-24 10:29
@faisal3389 Yeah thats nothing to worry about, a lot of the integration tests are broken in the redesign branch because of the changes being made to the structure of the pages. We will fix these after the redesign is done.

**Comment by arun1595** [comment] 2017-04-25 21:55
Resolved in https://github.com/TheOdinProject/theodinproject/pull/434 by @faisal3389

**Closed by arun1595** 2017-04-25 21:55 UTC
Labels: Good for beginners, Help Wanted
