### ISSUE TITLE
Add “Continue” button and badge for selected path

### ISSUE THREAD

**Issue by drewstroshine** [TheOdinProject/theodinproject#4495] opened 2024-04-11 02:26 UTC
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

When clicking the "Resume" button on the https://www.theodinproject.com/paths page, it navigates to the course page instead of the last worked on and uncompleted lesson page. The "Resume" button is performing the same behavior as the "View" button. This is in contrast to the "Resume" button on the https://www.theodinproject.com/dashboard page which is working as intended and navigating to that last worked on and uncompleted page.

### How to reproduce

1. Sign in
2. Navigate to the https://www.theodinproject.com/paths page either by clicking the "View Full Curriculum" button or the "All Path" link in the header
3. Click the "Resume" button of a path currently in progress and with at least one completed lesson
4. The "Resume" button navigates to the course page of the path and not the lesson currently being worked on

### Expected behavior

1. Sign in
2. Navigate to the https://www.theodinproject.com/paths page either by clicking the "View Full Curriculum" button or the "All Path" link in the header
3. Click the "Resume" button of a path currently in progress and with at least one completed lesson
4. The "Resume" button navigates to the lesson currently being worked on

### What browsers are you seeing the problem on?

Chrome, Safari

### What OS are you using?

MacOS

### Additional Comments

It appears the "Resume" button on the https://www.theodinproject.com/dashboard page is working as expected so if that same behavior could be transferred to the "Resume" button on the https://www.theodinproject.com/paths page then that might easily fix the bug.

**Comment by KevinMulhern** [comment] 2024-04-13 15:27
Thanks for making this issue. This isn't a bug, its intended behaviour on our Paths page. We use "Resume" instead of 
"View" to indicate which path the learner has selected. But, this has been brought up before https://github.com/TheOdinProject/theodinproject/issues/3230, so I wouldn't be against finding a better, less confusing way to differentiate a selected path from the rest - if anyone has any good ideas?

**Comment by MaoShizhong** [comment] 2024-04-13 17:07
Perhaps going back to "View" but having a marker of some sort (e.g. "Currently selected") on a selected pathway card?

**Comment by drewstroshine** [comment] 2024-04-14 16:51
What if for a selected path, there is only one "Continue" button instead of the "Resume" and "View" button? My thinking is the "Continue" button would differentiate it from the "Resume" button on the Dashboard page, and it would signify continuing on your path vs resuming your progress on your course?

<img width="594" alt="image" src="https://github.com/TheOdinProject/theodinproject/assets/32473424/13829217-65e3-4d7f-8f47-b6567a51ab9c">

**Comment by KevinMulhern** [comment] 2024-04-16 17:27
> What if for a selected path, there is only one "Continue" button instead of the "Resume" and "View" button? My thinking is the "Continue" button would differentiate it from the "Resume" button on the Dashboard page, and it would signify continuing on your path vs resuming your progress on your course?

This sounds solid, I really like the thought process behind this. 


I like the idea of combining "Continue" with a marker/flag - We have a badge component we could use. One of the top corners or beside the title could work:

<img width="1011" alt="Screenshot 2024-04-16 at 18 21 36" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/f04d8bcb-2fa4-4000-a373-aa521477247d">


<img width="1136" alt="Screenshot 2024-04-16 at 18 20 54" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/f75de89c-dada-4292-ae61-9bda4e4affa6">


Although, that might be overkill if "continue" differentiates it enough?

**Comment by MaoShizhong** [comment] 2024-04-16 17:29
I like the idea of both the lone "continue" button *and* the "selected" badge (either placement looks :fire:)

**Comment by davidha99** [comment] 2024-04-16 17:36
> I like the idea of both the lone "continue" button _and_ the "selected" badge (either placement looks 🔥)

I like that idea too

**Comment by drewstroshine** [comment] 2024-04-16 17:39
> > I like the idea of both the lone "continue" button _and_ the "selected" badge (either placement looks 🔥)
> 
> I like that idea too

Same here 👍

**Comment by KevinMulhern** [comment] 2024-04-19 19:54
Thanks @davidha99, I've assigned it to you.

**Closed** 2024-05-15 16:51 UTC
Labels: Type: Enhancement
