### ISSUE TITLE
Bug: <outdated hyperlinks of faq page>

### ISSUE THREAD

**Issue by M-AminAlizadeh** [TheOdinProject/theodinproject#4515] opened 2024-04-25 05:09 UTC
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Bug description

Hey there
I was checking the [FAQ](https://www.theodinproject.com/faq) page and I realized in the question `Which technologies can one expect to learn from The Odin Project?` in the answer part some links like `NodeJs`, `JavaScript`, `Ruby on Rails` and other links are broken and when I click on them it redirects me to `404page`

### How to reproduce

1. visit [FAQ](https://www.theodinproject.com/faq)
2. Check the below section
![image](https://github.com/TheOdinProject/theodinproject/assets/67329484/78aaa63d-f7b0-4e6c-b048-2c13d2adc8c2)
3. Click on underlined links like `NodeJs`, `JavaScript`, `Ruby on Rails`
4. You will see below page
![image](https://github.com/TheOdinProject/theodinproject/assets/67329484/a4ea00f2-b18e-4ebd-b9ae-36cd7b689fa6)

### Expected behavior

It should redirect a user to the proper pages in the curriculum

### What browsers are you seeing the problem on?

Firefox

### What OS are you using?

Ubuntu

### Discord Name

Amin Alizadeh

### Additional Comments

I can fix this error it's simple but important to UX

**Comment by davidha99** [comment] 2024-04-26 17:44
I'm able to reproduce this issue on Chrome and Safari (MacOS), the broken links:
- Foundations course
- HTML and CSS
- Javascript
- NodeJS

**Comment by SChurch89** [comment] 2024-04-30 03:36
I have thoroughly read and understand [The Odin Project Contributing Guide] I would like to work on this issue?

**Comment by MaoShizhong** [comment] 2024-05-12 22:06
Sorry it's taken so long - thanks for raising this issue @M-AminAlizadeh, I've assigned this to you since you've specified you wish to work on this.
Let us know if you run into any issues.

**Closed** 2024-05-28 12:47 UTC
Labels: Type: Bug, Status: Needs Review
