### ISSUE TITLE
Bug: The website is highly zoomed in when I open my browser again with the TOP tab open.

### ISSUE THREAD

**Issue by syedubaid11** [TheOdinProject/theodinproject#3434] opened 2022-10-15 10:46 UTC
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: PC
-   OS: Windows 10
-   Browser:  Brave 
-   Version: 

**5. Additional Information:**

**Comment by KevinMulhern** [comment] 2022-10-15 10:49
Sounds like it may be related this issue: https://github.com/TheOdinProject/theodinproject/issues/2664#issuecomment-1278019437

Can you fill out the browers and OS information in the bug report please @syedubaid11?

**Comment by syedubaid11** [comment] 2022-10-15 11:01
> Sounds like it may be related this issue: https://github.com/TheOdinProject/theodinproject/issues/2664#issuecomment-1278019437
> 
> Can you fill out the browser and OS information in the bug report please @syedubaid11?

Done.

And yes it's similar to the bug you mentioned

**Comment by KevinMulhern** [comment] 2022-10-15 11:34
Thanks @syedubaid11 💪

**Comment by avetisovi** [comment] 2022-10-15 18:47
I had the same bug when I was using Brave on Ubuntu 22. Can't reproduce it though.

**Comment by ChargrilledChook** [comment] 2023-05-20 10:18
Closing as no sign of this occurring for at least 5 months or so (from a cursory search of Discord).

**Closed** 2023-05-20 10:18 UTC
Labels: Type: Bug, Status: Help Wanted
