### ISSUE TITLE
Bug: Markdown preview doesn't work with <details> tag

### ISSUE THREAD

**Issue by kol3x** [TheOdinProject/theodinproject#4490] opened 2024-04-09 10:08 UTC
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Bug description

Markdown preview doesn't work with details tag, it just shows plain text

### How to reproduce

1. Go to https://www.theodinproject.com/lessons/preview
2.  Insert  
```html
<details>
  <summary>Epcot Center</summary>
  <p>Epcot is a theme park at Walt Disney World Resort featuring exciting attractions, international pavilions, award-winning fireworks and seasonal special events.</p>
</details> 
``` 
3. Go to preview version
4. Text is not hidden and not clickable

### Expected behavior

1. Go to https://www.theodinproject.com/lessons/preview
2.  Insert  
```html
<details>
  <summary>Epcot Center</summary>
  <p>Epcot is a theme park at Walt Disney World Resort featuring exciting attractions, international pavilions, award-winning fireworks and seasonal special events.</p>
</details> 
``` 
3. Go to preview version
4. Text is  hidden and unhidden on click.

### What browsers are you seeing the problem on?

Firefox

### What OS are you using?

Ubuntu

**Comment by CouchofTomato** [comment] 2024-04-09 16:08
@KevinMulhern Please take a look

**Comment by KevinMulhern** [comment] 2024-04-09 17:49
Thanks for reporting @kol3x - duplicate of https://github.com/TheOdinProject/theodinproject/issues/4488

**Closed by KevinMulhern** 2024-04-09 17:49 UTC
Labels: Type: Bug, Status: Needs Review

**Comment by kol3x** [comment] 2024-04-09 20:04
My bad :(
