### ISSUE TITLE
Bug: Dark Mode in "Add Solution" difficult to read.

### ISSUE THREAD

**Issue by DataMoshing** [TheOdinProject/theodinproject#3055] opened 2022-07-02 21:44 UTC
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**Description of the Bug:**

When navigating toward "Add Solution" in Dark Mode the GitHub repository URL along with the Live Preview URL the input text becomes rather challenging to see. The icons also get a bit lost in the background.
![Capture](https://user-images.githubusercontent.com/55223157/177016635-580d946b-bfca-4f26-9b34-924a10d38aaf.PNG)

**Expected Behavior:**
The expected behavior should be clear and readable just as Light Mode seen here.
![Capture2](https://user-images.githubusercontent.com/55223157/177017668-3c9f9996-3e2f-4adf-8f3b-24760e4d2e45.PNG)

**Desktop/Device:**
 Browser: Google Chrome on Windows

**Comment by joayo13** [comment] 2022-07-03 18:33
I changed the dark-mode color values recently in an issue, so that would be the cause behind this happening. I see that if I apply a var to the background-color of the input elements to apply the dark-input-bg-color it's then readable. I'd like to be assigned this issue as it would only be changing one css property to include dark-input-bg-color when necessary.

**Comment by KevinMulhern** [comment] 2022-07-03 19:28
It's all yours @DataMoshing

**Closed** 2022-07-03 21:48 UTC
Labels: Type: Bug, Status: In Progress
