### ISSUE TITLE
Enable Dark Mode on Odin Project Website

### ISSUE THREAD

**Issue by OkomoJacob** [TheOdinProject/theodinproject#2202] opened 2021-09-08 09:19 UTC
#### Description

I suppose enabling(Or providing for) Dark Mode/Theme in our homepage will enable users with all vision requirements to study at their own comfort zone with little vision strain.I  can help collaborate to implement that if incorporated in the project.

**Comment by twalton83** [comment] 2021-09-08 10:58
duplicate of #908

**Closed by twalton83** 2021-09-08 10:58 UTC
