### ISSUE TITLE
Sorting Project Submissions

### ISSUE THREAD

**Issue by JaeGif** [TheOdinProject/theodinproject#3820] opened 2023-05-24 05:03 UTC
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
Most people will often view project submissions from the same few people. I don't mean that these projects are bad, but that this student made a good quality project FIRST. Thus this project accumulates the most attention and other projects are buried below pages and pages of submissions no matter how good they are.

Building simple sorting options will allow students to get a better view of many different approaches to the same projects, from a wide variety of students. It's nice to see projects completed more recently, as well as very popular projects.

Some suggested solutions were either have the top 5 projects shown be the most liked, while the next 5 are the most recent. I like this idea, but I think that sorting/filtering is a more customizable and longer-term solution. 

Perhaps this is an issue for a different Feature Req., but I believe that adding a tagging feature could be another excellent solution on top of sorting, so students can add 1 tag per user to projects and sort based on tags as well as date submitted. (Only positive tags allowed), ex. "Clean Code" | "Clever" | "UI/UX" | "Robust" | "Alternative Stack" etc. The only negative tag I see being useful would be a "Broken Link" tag, as many project submissions are dead now that Heroku is no longer free. This feature would require DB changes though and is significantly more intensive. 

**2. Acceptance Criteria:**

- [ ] Basic submission sorting options, ex. "Most Liked", "Popular this week", "Popular this month" etc. 
- [ ] OPTIONAL: remember the user's preferences and by default sort by user's preferred choice.

**3. Additional Information:**
https://discord.com/channels/505093832157691914/1030363924178141195/1030363924178141195

The conversation was started here quite a while ago, but I don't think it's been followed up on. Couldn't find an open issue or another mention on the discord.

**Comment by ChargrilledChook** [comment] 2023-05-24 06:46
Duplicate of #2948

**Closed** 2023-05-24 06:46 UTC
Labels: Status: Needs Review
