### ISSUE TITLE
Bug: Bad display of content on iPad using Safari

### ISSUE THREAD

**Issue by erasmorojastech** [TheOdinProject/theodinproject#2718] opened 2022-03-13 20:00 UTC
Complete the following REQUIRED checkboxes:

-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The content doesn't display as it should. The final block we use to go to the next lesson displays at the beginning of the page. 

**2. How To Reproduce:**

1. Pick an iPad and open Safari
2. Go to TheOdinProject and log in
3. Visit a lesson page and see how the final block displays at the beginning

**3. Expected Behavior:**

I would expect that the content is displayed as it shows on a PC screen. With no issues of this kind.

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 
I was using an iPad Mini 1, with iOS 9.3.5 and safari.

**5. Additional Information:**

I use to read that on an iPad Pro 9.7" with iOS14, on safari too and had the same result. The final block just appear at the beginning

![Foto 13-3-22 10 44 02 a m](https://user-images.githubusercontent.com/73343862/158076824-60b221a8-6c8b-47b3-a14f-145f25d47b3a.png)

**Comment by KevinMulhern** [comment] 2022-03-13 23:20
We've tested this on 4 different iPads within the maintainer team @erasmorojastech, none of us can reproduce this issue 😅 

Is there anything different about your setup which could potentially cause this?

**Comment by erasmorojastech** [comment] 2022-03-14 00:44
Maybe I'm using an old version of safari and iOS. I'm using an iPad Mini 1st gen, iOS 9.3.5 on Safari

**Comment by KevinMulhern** [comment] 2022-03-14 00:48
> I use to read that on an iPad Pro 9.7" with iOS14, on safari too and had the same result. 

You mentioned it was happening on an iPad pro as well, can you take a screenshot of that please? just so we can see if there are any differences/clues as to what's going on.

**Comment by erasmorojastech** [comment] 2022-03-14 01:05
I can't do that because I sold that iPad and only have the old one... But I checked on an iPhone 12 Pro Max and goes well

But check this... Look how the content is displayed...

![Foto 13-3-22 10 52 58 p m](https://user-images.githubusercontent.com/73343862/158088205-4b5ffc76-d16b-4150-9a47-c44b71cbcf75.png)

**Comment by ChargrilledChook** [comment] 2022-07-09 02:06
Hey @erasmorojastech, since no one on the team can reproduce this and we're not seeing any other reports, I'm going to close this. We're currently making some updates to the site's CSS that may also address these issues.

If you can give us any other information / ways we can reproduce this then feel free to share it here and we can open this and have a look again. 

Thanks for the report!

**Closed by ChargrilledChook** 2022-07-09 02:06 UTC
Labels: Type: Bug, Type: CSS
