### ISSUE TITLE
About page has incomplete styling

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/theodinproject#2536] opened 2022-01-13 15:05 UTC
On [the About page](https://www.theodinproject.com/about) there are three elements that are white:

- `div .contribute`
- ` section .overview`
- an alternate logo of TOP

I sadly have no idea how to contribute to this project _yet_ :(

**Comment by KevinMulhern** [comment] 2022-02-01 19:36
Duplicate of https://github.com/TheOdinProject/theodinproject/issues/2537

**Closed by KevinMulhern** 2022-02-01 19:36 UTC
Labels: Type: Design, Status: Investigating
