### ISSUE TITLE
Bug: Clicking on All Paths Nav Link Makes the Community Nav Link Active

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1832] opened 2021-04-11 00:40 UTC
### Steps to Reproduce
1. Click the "All Paths" nav link.
2. The community nav link is also active (highlighted in black)💥

### Expected Behaviour
 1. Click the "All Paths" nav link.
2. Only the All Paths nav link is active

### Additional Information

Screen shot: 
![Screenshot 2021-04-11 at 01 30 31](https://user-images.githubusercontent.com/7963776/114288338-cc4ef380-9a66-11eb-8d19-e7f88b98bfe3.png)

**Comment by BrianWisniewski** [comment] 2021-04-17 01:49
I would be happy to try this out. Can't guarantee I'll figure it out but it's worth a shot!

**Comment by KevinMulhern** [comment] 2021-04-20 21:51
Hi @BrianWisniewski, sorry mate I missed your comment on this. Do you still want to work on this one? I'll assign to you if you do.

**Comment by BrianWisniewski** [comment] 2021-04-21 15:44
I would still like to do this but I probably can't do it until this weekend if that's ok with you. If it's a priority someone else is welcome to work on it.

**Comment by KevinMulhern** [comment] 2021-04-21 16:54
No thats fine, theres no rush on this one @BrianWisniewski 😄

**Comment by Shyam-Sundar-Bharathi** [comment] 2021-04-26 13:23
@KevinMulhern I'd like to work on this. I believe I can fix it. I see the issue is already assigned to someone else. Can I still try?

**Closed** 2021-04-27 16:58 UTC
Labels: Help Wanted, UI
