### ISSUE TITLE
Redesign: Bug with full screen dropdown when scrolling on mobile

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#505] opened 2017-05-04 22:36 UTC
Tested and identified on an iphone6

To replicate open the full screen drop down on the navbar and scroll, the menu items will resize, the bottom login option sometimes vanishes too.

If you need any more information please tag me in the comments 😄

**Comment by codyloyd** [comment] 2017-05-05 10:31
the staging server does not have the latest navbar code... I'm not positive it'll fix the problem, but could you go ahead and deploy it again when you get a chance?

**Comment by KevinMulhern** [comment] 2017-05-05 12:13
👍 No problem

**Comment by codyloyd** [comment] 2017-05-05 12:41
ok.. as it is now, the problem still exists, but it is less of an actual problem because it's not hiding one of the menu options, so it feels less glitchy.  The issue arises because the window height changes when you scroll in a mobile browser.  I am going to try to make the dropdown overflow the height a little bit.. I think that may fix the error.

if not it's gonna take some deeper thinking 🗡

**Comment by codyloyd** [comment] 2017-05-05 13:08
I'm not sure this can be fixed with plain CSS.  I have a hack in mind where we use JS to throw a plain white div up under the menu when it's invoked, but I'm not super sure how well it'll work.

**Comment by KevinMulhern** [comment] 2017-05-05 15:42
No problem @codyloyd, it functions a lot better now 😄 
The menu items look a bit close together but thats less of a problem than the one before as you said. Thanks for looking into this man.

**Comment by codyloyd** [comment] 2017-05-11 00:40
OK.... I've been working on this for an hour with no luck. I think it is legitimately a browser bug 😢

could be wrong (this is often the case!)

**Comment by KevinMulhern** [comment] 2017-05-11 07:12
👍 no worries, thanks for looking into it Cody 😄 its a really weird bug. I'll ask a friend about this, he has probably encountered it before.

**Comment by RobPando** [comment] 2017-05-24 21:07
@codyloyd did you try giving the body a overflow hidden when dropdown menu is open? not sure what the problem is I don't see it, the only thing I see is that the page scrolls when the menu is open, which in my opinion shouldn't happen. Cant work on this since I dont know what wrong. Maybe this was fixed @KevinMulhern ?, but it might get fixed by preventing scroll when dropdown is open.

**Comment by KevinMulhern** [comment] 2017-05-24 23:56
@RobPando it hasn't been fixed yet. You can see it best when you view the staging site on a mobile device.

The nav items lose the spacing between them when you scroll.

**Comment by codyloyd** [comment] 2017-05-25 00:00
Only if the browser is showing its bottom toolbar as well...    
  
  
  
  
  

  
  
>

**Comment by KevinMulhern** [comment] 2017-05-25 21:21
@RobPando That doesn't look like its fixed it :(

Heres how I am recreating it using an iphone 6s on chrome:

1. Go to the staging site
2. open the nav bar
3. scroll up and down

The nav items seem to loose the spacing between them and a gap appears at the bottom of the screen where you can see the page under the menu being scrolled through.

It works better on safari ios, the gap is still there but the nav items keep their spacing.

After messing around with this on the browser chrome inspector I think its flexbox which is causing the pain.

**Comment by RobPando** [comment] 2017-05-26 06:52
@KevinMulhern I see now... the dropdown items also breaks completely when you put the phone on landscape, Ill look into it later. I didn't see that before, but at least that right whitespace is not there anymore. 😅

**Comment by davidchappy** [comment] 2017-06-29 17:45
@KevinMulhern I'm working on this. Looks like at least part of the issue is [using 100vh in iOS](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser)

**Comment by davidchappy** [comment] 2017-06-29 22:16
Just submitted a PR for this. 

[Here's a working version](https://limitless-headland-70035.herokuapp.com/home) you can check out.

**Closed** 2017-07-02 22:28 UTC
Labels: bug, Help Wanted
