### ISSUE TITLE
Feature: Previous lesson button

### ISSUE THREAD

**Issue by DoviMaj** [TheOdinProject/theodinproject#1639] opened 2021-01-10 18:57 UTC
I think it would be really helpful to have a button to go back to the previous lesson. From the discussions in the Discord channel, and this issue https://github.com/TheOdinProject/theodinproject/issues/1002 it seems to be a feature that has demand for and worth implementing. it will help students navigate through lessons, and not needing to open the whole course to find the previous lesson.

**Comment by I3uckwheat** [comment] 2021-01-10 23:38
Duplicate of #1002 closing.

**Closed by I3uckwheat** 2021-01-10 23:38 UTC

**Comment by DoviMaj** [comment] 2021-01-10 23:42
@I3uckwheat ? i was told to open a new issue since the previous one was closed

**Comment by I3uckwheat** [comment] 2021-01-10 23:45
@DoviMaj All the context is in the previous issue, no need to make a new one.

**Comment by DoviMaj** [comment] 2021-01-10 23:47
but the previous one is closed @I3uckwheat :thinking:

**Comment by DoviMaj** [comment] 2021-01-10 23:52
I only wanted to know if this is something that is wanted and can be implemented... if so then I could take a look at it and try it or someone else could pick it up. don't get how a closed issue will help us here

**Comment by I3uckwheat** [comment] 2021-01-10 23:56
@DoviMaj You could comment on the old issue. Duplicates split the discussion. 

As stated in the old issue as well by @KevinMulhern, there was a study done and the previous lesson button was proven ineffective. We also discussed this on discord: https://discord.com/channels/505093832157691914/540903304046182425/767752006601277510

**Comment by I3uckwheat** [comment] 2021-01-10 23:57
This also doesn't seem like a good use of our time to worry about and maintain at this point.

**Comment by DoviMaj** [comment] 2021-01-11 00:03
well there was interest in the button both in the issue mentioned, you also said it would be useful https://discord.com/channels/505093832157691914/540903304046182425/767757658195230771 and yesterday on the channel https://discord.com/channels/505093832157691914/540903304046182425/797891254616195073, but if u think its a waste of time il shut up

**Comment by I3uckwheat** [comment] 2021-01-11 00:07
@DoviMaj Yes, I did at the time. However, realizing there was a study done on this already in the past that has proven it's not useful.

**Comment by DoviMaj** [comment] 2021-01-11 00:09
only because a button is less used than others means it's not useful?

**Comment by I3uckwheat** [comment] 2021-01-11 00:13
@DoviMaj Adding clutter and more things to maintain on the website is not worth the time if a very low percentage of users find that useful.

**Comment by twalton83** [comment] 2021-01-11 00:16
I did like the idea, @DoviMaj, but as I am a newer maintainer and didn't know the complete history behind the prior conversations about this feature, I agree that if a study has been done and it was proven to just not be worth it, our time is better spent implementing things with more importance, like new curriculum.

**Comment by DoviMaj** [comment] 2021-01-11 00:36
ok. thanks for the clarifications guys. @I3uckwheat ++ @twalton83 ++ u are the real MVP
